### ISSUE TITLE
vscode can't install

### ISSUE THREAD

**Issue by BigBigPlant** [jmrog/vscode-nuget-package-manager#37] opened 2019-04-27 15:55 UTC
![1](https://user-images.githubusercontent.com/37919956/56851985-dd6ccb80-6947-11e9-8aae-2d635668b447.PNG)
 Why?

**Comment by liuziyuan** [comment] 2019-05-10 01:48
I also has this issue at Ubuntu 18.04,and I used .net core v2.2

**Comment by jmrog** [comment] 2019-05-10 02:34
Thanks for these reports. I'll try to investigate this very soon.

**Comment by jmrog** [comment] 2019-05-21 20:31
I've tried to reproduce this many times, but I never have a problem. Can one of you please confirm whether this is still happening for you? Can you perhaps provide me with more details, such as VSCode version, operating system, and any other information you think might be relevant (e.g., whether you are behind a proxy of some kind)?

**Comment by jmrog** [comment] 2019-05-21 20:32
Can you also mention where in the world you are located geographically? I'm starting to suspect that there could be an issue in a particular region.

**Comment by jmrog** [comment] 2019-05-22 14:13
Duplicate of #38. The issue appears to be caused by the way certain servers are configured for users in China. Please follow-up there. (Closing this issue in favor of that one.)

**Closed by jmrog** 2019-05-22 14:13 UTC
Labels: duplicate
